services:
  otbr:
    image: openthread/border-router
    container_name: otbr
    network_mode: host
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /var/lib/otbr:/data
    env_file:
      - /home/agsense/sysMgmt/config_otbr_docker/otbr-env.list
    restart: always
